# Generated by Django 4.1.4 on 2022-12-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horas_disponiveis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
